reports totals better

diff --git a/chksyntax b/chksyntax
--- a/chksyntax
+++ b/chksyntax
@@ -41,7 +41,7 @@ usage() {
     echo "  -h this help"
     echo "  -r recursive"
     echo "  -v verbose, output even when passed"
-    echo "  -d dont ignore unknown files"
+    echo "  -i ignore unknown files"
     exit
 }
 
@@ -65,7 +65,8 @@ test_script() {
         return 0
     }
     $@ > /dev/null 2>&1 && {
-        test $v -eq 1 && echo -e "Passed [$1]\t: ${@: -1}"
+        test $verbose -eq 1 && echo -e "Passed [$1]\t: ${@: -1}"
+        passed=`expr $passed + 1`
         return 0
     }
     errors=`expr $errors + 1`
@@ -77,18 +78,16 @@ test_script() {
 
 ############ Command line arguments #######
 paths=()
-m=1
-d=0
-v=0
-total=0
-errors=0
-skipped=0
+maxdepth=1
+ignore=0
+verbose=0
+
 for arg in "$@" ; do
     if [[ ! $arg =~ ^- ]] ; then paths+=($arg) ; fi
     test "$arg" == "-h" && usage
-    test "$arg" == "-r" && m=99
-    test "$arg" == "-d" && d=1
-    test "$arg" == "-v" && v=1 && d=1
+    test "$arg" == "-r" && maxdepth=99
+    test "$arg" == "-i" && ignore=1
+    test "$arg" == "-v" && verbose=1
 done
 
 if [[ ${#paths[@]} == 0 ]] ; then paths+='./' ; fi
@@ -103,9 +102,13 @@ for s in ${scripts[@]} ; do
 done
 
 ############ Main Program  ##########
+total=0
+passed=0
+errors=0
+skipped=0
 
 for path in ${paths[@]} ; do
-    files=`find $path -maxdepth $m -type f`
+    files=`find $path -maxdepth $maxdepth -type f`
     for file in ${files} ; do
         test -s $file || continue;
         h=`head -n1 $file` # get header here rather than everytime
@@ -137,16 +140,18 @@ for path in ${paths[@]} ; do
         done
         test $tested -eq 1 && continue;
 
-        test $d -eq 1 || continue;
+        test $ignore -eq 0 || continue;
         echo -e "Unknown script\t: $file"
+        skipped=`expr $skipped + 1`
+        total=`expr $total + 1`
     done
 done
 
-test $skipped -eq 0 || echo "Skipped $skipped";
+test $passed -eq $total || echo -e "Total\t: $total";
+test $skipped -eq 0 || echo -e "Skipped\t: $skipped";
 test $errors -eq 0 || { 
-    echo "Total $total";
-    echo "Errors: $errors";
+    echo -t "Errors\t: $errors";
     exit 1;
 }
-echo "All $total files passed syntax checks";
+echo -e "Passed\t: $passed/$total";
 exit 0;
